### ISSUE TITLE
Decimal BIF implementation checklist

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#118]
<a href="http://github.mtv.cloudera.com/wesm"><img src="https://gravatar.com/avatar/d95cdeb33b3463eba00e4064fbd030d6?d=https%3A%2F%2Fidenticons.github.com%2Ff3f27a324736617f20abbf2ffd806f6d.png&r=x" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wesm](http://github.mtv.cloudera.com/wesm)**
_Tuesday Mar 03, 2015 at 18:29 GMT_
_Originally opened as http://github.mtv.cloudera.com/wesm/ibis/issues/118_

---

Follow up to #60 
- [x] Support for BIF's that accept and return decimals
  - [x] ABS()
  - [x] CEIL()
  - [x] COALESCE()
  - [x] FLOOR()
  - [x] FNV_HASH()
  - [x] GREATEST()
  - [x] IF()
  - [x] ISNULL()
  - [x] LEAST()
  - [x] NEGATIVE() (WM not implementing in favor of `-expr`)
  - [x] NULLIF()
  - [x] POSITIVE() (WM 2015-04-13 not implementing as kind of useless)
  - [x] PRECISION()
  - [x] ROUND()
  - [x] SCALE()
  - [x] TRUNCATE() (WM 2015-04-13 cannot find in the impala documentation, skipping)
  - [x] ZEROIFNULL()
