### ISSUE TITLE
Dask Backend TODO Items

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#2537]
Breaking up https://github.com/ibis-project/ibis/pull/2400 into multiple pieces, updating this issue as we worth through each step. 

- [ ] Add a trivial skeleton + CI https://github.com/ibis-project/ibis/pull/2536
- [ ] Pull the dispatcher things from the pandas backend and the rest of the supporting files outside /execution/ (client, core, trace), importing from pandas where possible.
- [ ] Known working-ish pieces (pieces in /execution/).
- [ ] Adding docs + whatsnew note for work completed
- [ ] TODOs for windowing, aggregations, etc (i.e. things that aren't working yet in the consolidated PR).
