### ISSUE TITLE
refactor: remove deprecations

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2863]
Before releasing, we need to remove the deprecations from previous releases.

**Introduced in Ibis 2.0**
- [ ] `list_schema` on SQLAlchemy backends (#2862)
- [x] `expr.verify()` and `ibis.<backend>.verify()` (#2866)
- [ ] `Client.database` and `Database` class (#2897)
- [ ] `Client.exists_table` (#2905)

**Comment by jreback** [comment]
no these can't be removed for 2.0; need another version for that

**Comment by datapythonista** [comment]
Yep, clarified the description, 2.0 is when they are being introduced. I think we can remove them in 3.0, but leaving it open for now.

**Comment by cpcloud** [comment]
We have the `@deprecated` decorator now, so it should be straightforward to figure when a thing was deprecated and remove it.

However, we still need to come up with a policy. Let's open up a GitHub Discussion and talk about it.
