### ISSUE TITLE
docs: Create and Populate How-To Guides

### ISSUE THREAD

**Issue by p-a-a-a-trick** [ibis-project/ibis#4385]
# Create+Populate How-To Guides

There is a lack of how to guides on the website. Let's make a list of them and start populating a useful section for code schematics.

I hope to keep this issue up as a rolling list of How to Guides, so if you stumble on this and your need isn't included in the docs or this list, then comment your request here!

## v3.2

- [x] How to compute the top k records
- [x] How to register tables in a DuckDB backend [#4386](https://github.com/ibis-project/ibis/pull/4386)
- [x] How to ffill and bfill using window functions ([source](https://github.com/ibis-project/ibis/wiki/ffill-and-bfill-using-window-functions)) [#4402](https://github.com/ibis-project/ibis/pull/4402)

## v4.0
- [x] How to join a table expression to a pandas dataframe ([merged](https://github.com/ibis-project/ibis/pull/4323)) ([docs PR](https://github.com/ibis-project/ibis/pull/4679))
- [x] (WIP) How to chain ibis expressions (`_` API) (#4914)
- [x] How to [sessionize](https://knowledge.dataiku.com/latest/courses/advanced-code/python/sessionization.html) a log of events based on the elapsed time between successive transactions for a give user identifier (#4843).
- [ ] How to convert column structures into columns (`unpack`)

## v4.1+
- [ ] How to create a table with a user-defined schema and efficiently load a large CSV file into it (handling common annoying things like the choice of the separator and custom date / time formats).
- [ ] How to efficiently sample random rows from a large table (or expr) to quickly compute approximate descriptive statistics such as quantiles.
- [ ] How to perform an `asof_join` ([source](https://github.com/ibis-project/ibis/wiki/%60asof_join%60-in-SQL))
- [ ] How to interpolate dates (and/or other sequences)
- [ ] [maybe?] How to use Ibis to generate and save Substrait/SQL
- [ ] How to create a backend (incl. a section on SQLAlchemy backends specifically, but should focus on min requirements to get one up and running w/o SQLAlch)
- [ ] How to chain joins (unknown if this should even be a how-to guide, but if [#4309](https://github.com/ibis-project/ibis/issues/4309) is a fact of life then we should add this)

Let me know if you have any ideas and I'll add them to the list.

**Comment by cpcloud** [comment]
I the things in the wiki are useful bits of information to put in the how-tos.

**Comment by ogrisel** [comment]
Here are some more ideas:

- How to create a table with a user-defined schema and efficiently load a large CSV file into it (handling common annoying things like the choice of the separator and custom date / time formats).

- How to [sessionnize](https://knowledge.dataiku.com/latest/courses/advanced-code/python/sessionization.html) a log of events based on the elapsed time between successive transactions for a give user identifier.

For the first item about CSV loading, I don't know if there is a standard way to use the `COPY` statements of popular databases from ibis. Personally I used a `raw_sql` command with duckdb to be able to specify a custome date format in a recent experiment.

**Comment by ogrisel** [comment]
@p-a-a-a-trick I made a typo in the word "sessionize".

**Comment by p-a-a-a-trick** [comment]
> @p-a-a-a-trick I made a typo in the word "sessionize".

Got it; thanks @ogrisel! I'll probably knock a few more of these out in the next couple of months.  Let me know if you have any more ideas—I can't guarantee they'll get in before the next release but I hope to have most (if not all) of these in before then.

I hope to keep this issue as a rolling list of requested How To guides, not sure if it'll ever be closed.

**Comment by ogrisel** [comment]
For reference the 3 how-tos above stems for my first time experience with ibis and duckdb which is quite pleasant so far:

https://github.com/soda-inria/survival-analysis-benchmark/tree/main/datasets/kkbox_churn

**Comment by ogrisel** [comment]
Another good related post on how to sessionize data (using polars):

- https://www.pola.rs/posts/the-expressions-api-in-polars-is-amazing/

**Comment by NickCrews** [comment]
I'll throw in data import/export. I find guidance on this topic currently pretty limited in the docs, but this is a step that every single user is going to do. [Here is a nice example from vaex](https://vaex.readthedocs.io/en/latest/guides/io.html). There are other good examples of How-tos there as well.

**Comment by lostmygithubaccount** [comment]
closing this per recent docs updates, how-tos available on the site: https://ibis-project.org/how-to/configure/basics
