### ISSUE TITLE
meta: Release and launch geospatial support for DuckDB

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8034]
**Acceptance criteria**: Geospatial operations are supported for DuckDB, the default backend. This brings a great local option for small-to-medium geospatial data processing in Ibis.

TODOs:

- [x] geospatial implementation
- [x] initial geospatial blog
- [x] dev guru geospatial blog
- [x] add an example for geospatial data
- [x] improve docstrings for geospatial operations

**Comment by lostmygithubaccount** [comment]
**Weekly Update**:
2024-01-18

- Second geospatial blog was released: [docs(blog-post): replicate spatial dev guru blog ibis#7973](https://github.com/ibis-project/ibis/pull/7973), and also publicized in social media. (twitter, linkedin, and reddit)

At the moment we do have support for 30+ geospatial functions, but we are lacking of better documentation, this two issues are meant to tackle that problem:

- [feat: add an example geo dataset to ](https://github.com/ibis-project/ibis/issues/7958)[ibis.examples](https://github.com/ibis-project/ibis/issues/7958)[ ibis#7958](https://github.com/ibis-project/ibis/issues/7958)
- [docs: add example docstrings to geospatial methods ibis#7959](https://github.com/ibis-project/ibis/issues/7959)

This PR just got merged, which to support geospatial literals on duckdb, which will make creating examples that are more compelling:

- [feat(duckdb-geospatial): support for literals ibis#7975](https://github.com/ibis-project/ibis/pull/7975)

(copying over last week's update on behalf of Naty)

**Comment by ncclementi** [comment]
## Weekly update 
2024-01-24

Only pending item to consider the meta issue done is
- https://github.com/ibis-project/ibis/issues/7959 (there were couple of hiccups that block progress, but should be a PR open soon)

**Comment by ncclementi** [comment]
## Weekly update 
2024-01-31

This PR was https://github.com/ibis-project/ibis/pull/8128, and this completes the epic.

**Comment by ncclementi** [comment]
No update here as this is complete. What do we want to do with this epic? Maybe a tag to mark it as completed, or edit the title and add [completed]

**Comment by lostmygithubaccount** [comment]
let's go with `[DONE` in the PR title, I've done that for now here -- might come up with something better later

**Comment by lostmygithubaccount** [comment]
closing per discussion -- great work @ncclementi especially and everyone who's helped out here!
