### ISSUE TITLE
docs: updated roadmap blog + GH project

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8852]
We published our first roadmap blog and made the roadmap public on a GH project
a few months ago: https://ibis-project.org/posts/roadmap-2024-h1/.

Since, we've decided to track the weekly updates for the core Ibis team at VoDa
in an internal system. Last quarter, we were updating on the GitHub issues and
duplicating those updates over to the internal system.

This quarter, we've decided to give weekly updates directly in the internal
system. In my view, it no longer makes sense to continue maintaining the
`roamdap` issues that show up in the GitHub project and attempting to keep it
in sync with internal reporting.

Instead, we should continue publishing updated roadmap blogs when applicable
(perhaps not every quarter) and giving updates on important GitHub issues as it
makes sense. We may look to revive the GH project at a future time, particularly
as the project gains more contributors outside VoDa.

For now, I propose/will implement:

- [ ] closing the existing `roadmap` issues across various repos
- [ ] closing the respective milestones for the `roadmap` issues
- [ ] editing the GitHub project to remove the roadmap view
- [ ] write and publish and updated roadmap blog
