### ISSUE TITLE
[meta] documentation improvements in 2024

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8857]
The purpose of this issue is to track various documentation improvements to be
made in mid-2024.

P0:

- [x] https://github.com/ibis-project/ibis/issues/8852
- [ ] https://github.com/ibis-project/ibis/issues/8853
- [ ] https://github.com/ibis-project/ibis/issues/8854
- [ ] https://github.com/ibis-project/ibis/issues/8855
- [x] https://github.com/ibis-project/ibis/issues/8856

P1:

- [ ] https://github.com/ibis-project/ibis/issues/8434
- [ ] https://github.com/ibis-project/ibis/issues/8090

P2:

- [ ] https://github.com/ibis-project/ibis/issues/8730
- [ ] https://github.com/ibis-project/ibis/issues/8514

**Comment by lostmygithubaccount** [comment]
Improvements have been made to the home page. There are still several TODOs, generally on track by end of June. I've been out of office and occasionally focused on other things, but it should only take a few weeks to:

- revamp our pandas tutorial and create new PySpark and Polars user tutorials
- revamp our how-to guides per the outlined issue
- good progress on API docs coverage and some reorganization
- a few blogs

Conceptual documentation may be dropped from scope.

We should organize a docs hackathon after (or before?) some of this work is done. Perhaps in July.
