### ISSUE TITLE
[meta] Ibis expression API stability

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8996]
**Acceptance criteria**: the Ibis user-facing expression API is stabilized for 10.0+. While we will always reserve the right to make breaking changes, we are now in the place where stability is important for production dependencies. Organizations choosing Ibis should feel confident their code will work with minimal effort when upgrading to new versions.

TODOs:

## P1

**dtype or type or cast**
- [x] https://github.com/ibis-project/ibis/issues/8833 

 **refactor**
 - [x] https://github.com/ibis-project/ibis/issues/7276 (associated PR: https://github.com/ibis-project/ibis/pull/9300)
 - [x] https://github.com/ibis-project/ibis/issues/9311 (associated PR: https://github.com/ibis-project/ibis/pull/9344)
 - [ ] https://github.com/ibis-project/ibis/issues/7252 (associated PR https://github.com/ibis-project/ibis/pull/9385)
 
**dtype or type or cast**
- [x] https://github.com/ibis-project/ibis/issues/8989 (draft PR open https://github.com/ibis-project/ibis/pull/9034)
- [ ] https://github.com/ibis-project/ibis/issues/8289 (PR open https://github.com/ibis-project/ibis/pull/8666 needs work)

## P2
**refactor or deprecate or breaking changes**
- [ ] https://github.com/ibis-project/ibis/issues/8333 

**dtype or type**
- [ ] https://github.com/ibis-project/ibis/issues/7331
- [ ] https://github.com/ibis-project/ibis/issues/7133  

    
**other**
- [ ] https://github.com/ibis-project/ibis/issues/7280 (PR in progress https://github.com/ibis-project/ibis/pull/9039) (new PR waiting review: https://github.com/ibis-project/ibis/pull/9096)

**Comment by gforsyth** [comment]
I ended up cataloging a bunch of issues that are more related to this than to #8994, I'll list them here:

* #7276 
* #8333 
* #9000 (this needs to wait until after probably 9.1)
* `read_in_memory` or `create_table`
  * #8133 
  * #6593 
  * #8622 
* #8584 
* #8735
* #8898
* #8866
* #8833 
* #8382 
* #8727 
* #5913 
* #7280 
* #7252 

Also, there's not an issue for this, but we should standardize our usage of keyword-only arguments and expand their usage dramatically.

**Comment by ncclementi** [comment]
After looking I think all of these are also part of Ibis expression API stability, dumping them here, I'll organize them by priority soon. 

DType, mapping and cast related
- https://github.com/ibis-project/ibis/issues/5316
- https://github.com/ibis-project/ibis/issues/5707
- https://github.com/ibis-project/ibis/issues/7331
- https://github.com/ibis-project/ibis/issues/7133
- https://github.com/ibis-project/ibis/issues/8479
- https://github.com/ibis-project/ibis/issues/8019
- https://github.com/ibis-project/ibis/issues/8138
- https://github.com/ibis-project/ibis/issues/9026
- https://github.com/ibis-project/ibis/issues/8604
- https://github.com/ibis-project/ibis/issues/8697
- https://github.com/ibis-project/ibis/issues/8989
- https://github.com/ibis-project/ibis/issues/8573


Pretty-printing: 
- https://github.com/ibis-project/ibis/pull/9043

Other
- https://github.com/ibis-project/ibis/issues/8289

**Comment by ncclementi** [comment]
## Weekly Update 
06/05/2024

- https://github.com/ibis-project/ibis/issues/8833https://github.com/ibis-project/ibis/issues/8833https://github.com/ibis-project/ibis/issues/8833 (closed via https://github.com/ibis-project/ibis/pull/9265)


- https://github.com/ibis-project/ibis/issues/8996 (PR under review https://github.com/ibis-project/ibis/pull/9300)


- https://github.com/ibis-project/ibis/issues/8989 (closed via community PR https://github.com/ibis-project/ibis/pull/9034)

- https://github.com/ibis-project/ibis/issues/8289 is being broken in multiple PR that Nick Crews is working on. Some have being merged:

https://github.com/ibis-project/ibis/pull/9305
https://github.com/ibis-project/ibis/pull/9306
https://github.com/ibis-project/ibis/pull/9302

The main one is still work in progress. https://github.com/ibis-project/ibis/pull/8666

**Comment by ncclementi** [comment]
## Weekly Update 
06/13/2024

Closed as complete:

- https://github.com/ibis-project/ibis/issues/7276
- https://github.com/ibis-project/ibis/issues/9311

Started and in progress: 
- https://github.com/ibis-project/ibis/issues/7252 

Note: 
https://github.com/ibis-project/ibis/issues/8289 is being further splitted https://github.com/ibis-project/ibis/pull/8666#issuecomment-2165890957

**Comment by ncclementi** [comment]
closing in favor of https://github.com/ibis-project/ibis/issues/9638
