### ISSUE TITLE
[EPIC] Ibis in memory format stability

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#8997]
**Acceptance criteria**: Stabilize the in-memory format for Ibis.

TODOs:

- [ ]

**Comment by ncclementi** [comment]
Dropping here  issues  that correspond to this epic. 

## P0
- [ ] https://github.com/ibis-project/ibis/issues/8697 

## P1
- [ ] https://github.com/ibis-project/ibis/issues/8604
- [ ] https://github.com/ibis-project/ibis/issues/8573 (SD)
- [ ] https://github.com/ibis-project/ibis/issues/8019 (PR open https://github.com/ibis-project/ibis/pull/8784 needs review) 
- [ ] https://github.com/ibis-project/ibis/issues/5316

**Comment by cpcloud** [comment]
In progress document here https://github.com/ibis-project/ibis/pull/9128
