### ISSUE TITLE
docs: update contribution guide

### ISSUE THREAD

**Issue by p-a-a-a-trick** [ibis-project/ibis#9536]
### Please describe the issue

I was setting up a dev environment and ran into some issues by following the directions (trying to, anyways). I'm open to have missed/misread something, though.

Here's what I ran into with 30 minutes of at-least-sorta-trying:

# Setting up an environment

source: https://ibis-project.org/contribute/01_environment

- `conda/` no longer exists (used `conda install --file conda-lock/linux-64-3.11.lock`, not sure if I was supposed to do that)
- `just` not installed through conda method (needed to `conda install just`)
- `just docs-preview` did not work (probably missing from conda-lock) (output below)

just docs-preview output:

```
~/python/repos/ibis$ just docs-preview
quarto preview docs
sh: 1: quarto: not found
error: Recipe `docs-preview` failed on line 149 with exit code 127
```

# Contribute to the Ibis codebase

source: https://ibis-project.org/contribute/02_workflow

- "To run tests that do not require a backend: `pytest -m core`" raises "no module found pyarrow.tests" (`22053 deselected, 1 error in 9.12s`) (probably due to my choice of conda-lock/?)
- same issue as above after `just download-data` → pytest -m sqlite
    - pyarrow is installed, so that's not it(?)
- `just up postgres` does not work (docker not found; output below)

```
just up postgres
docker compose up --wait postgres
sh: 1: docker: not found
error: Recipe `up` failed on line 94 with exit code 127
```

# Tasks

I think this is all of them so far:

- [ ] update `conda install --file` command (probably `mamba` as well)
- [ ] confirm `just` is installed correctly with the previous command or provide directions to install it correctly
- [ ] confirm `just docs-preview` is the correct command to preview docs
- [ ] confirm that the `pyarrow.tests` module error when running core, sqlite, postgres (and possibly others) tests for the first time on a fresh environment after following the environment setup guide does not occur (guide addresses potential user error, tests do not rely on pyarrow, etc; dev's choice)
- [ ] either confirm that docker and other deps are installed during the environment setup or note docker and/or other deps should be installed by the user before running `just up <backend>` (a small blurb about how to do that effectively without permanently infecting your computer with docker would be helpful but not required)

There's probably more, but this is what I ran into this morning. Let me know if you need anything else. Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepyaman** [comment]
Thanks for the issue! We took a quick look through; more of the team will be back from SciPy next week:

> just docs-preview did not work (probably missing from conda-lock) (output below)

I'm not 100% sure (will need to verify), but it looks like Quarto may be available through Conda (see https://github.com/conda-forge/quarto-feedstock). That said, I think the route have taken so far is installing from their website: https://quarto.org/docs/get-started/

I think some docs-related packages also may not be there in the Conda environment files (I think @chloeh13q ran into `pydantic` not being there the other day). Seems we need to make sure these are up-to-date.

> conda/ no longer exists (used conda install --file conda-lock/linux-64-3.11.lock, not sure if I was supposed to do that)

`conda/` is there, but maybe, if you were thinking about `conda-lock`, it was removed in 9.0 (see https://github.com/ibis-project/ibis/pull/8242).

> just up postgres does not work (docker not found; output below)

Do you have Docker Desktop (or an equivalent) installed and started? This is necessary for "non-trivial" backends; see https://ibis-project.org/contribute/02_workflow#setting-up-non-trivial-backends.

Will leave this open, as it seems there are some opportunities for improving the docs, and we can make sure the things you raised are addressed.

**Comment by p-a-a-a-trick** [comment]
Actually, yeah I found it. No idea what was going on - I'm going to close this issue. Thanks @deepyaman !
