### ISSUE TITLE
[meta]: Expression IR performance

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#9828]
Issue to track work done regarding improving performance. 

## Issues: 
- [x] https://github.com/ibis-project/ibis/issues/9111
- [ ] https://github.com/ibis-project/ibis/issues/9639
- [ ] https://github.com/ibis-project/ibis/issues/9662

## PRs
- [ ] https://github.com/ibis-project/ibis/pull/9684
- [ ] https://github.com/ibis-project/ibis/pull/9698 
- [ ] https://github.com/ibis-project/ibis/pull/9676
- [ ] https://github.com/ibis-project/ibis/pull/9664
- [ ] https://github.com/ibis-project/ibis/pull/9646
- [ ] https://github.com/ibis-project/ibis/pull/9641
- [ ] https://github.com/ibis-project/ibis/pull/9644
- [ ] https://github.com/ibis-project/ibis/pull/9641
- [ ] https://github.com/ibis-project/ibis/pull/9556
- [ ] https://github.com/ibis-project/ibis/pull/9440
